const authors = [{
    author_no: '1',
    author_name: 'Adam Gran',
    university: 'University of Michigan',
    date_of_birth: '1980-01-11',
    h_index: 11,
    gender: 'm',
    collaborator: null,
},
{
    author_no: '2',
    author_name: 'Alice Walker',
    university: 'Atlanta, GA',
    date_of_birth: '1992-01-12',
    h_index: 12,
    gender: 'f',
    collaborator: 102,
},
{
    author_no: '3',
    author_name: 'Bill Bryson',
    university: 'Durham University ',
    date_of_birth: '1979-05-24',
    h_index: 13,
    gender: 'm',
    collaborator: 103,
},
{
    author_no: '4',
    author_name: 'David Foster',
    university: 'Kent, UK',
    date_of_birth: '1984-04-09',
    h_index: 14,
    gender: 'm',
    collaborator: 104,
},
{
    author_no: '5',
    author_name: 'David McCullough',
    university: ' Yale University ',
    date_of_birth: '1988-10-21',
    h_index: 15,
    gender: 'm',
    collaborator: 105,
},
{
    author_no: '6',
    author_name: 'Dean Koontz',
    university: ' Yale University ',
    date_of_birth: '1988-10-21',
    h_index: 16,
    gender: 'm',
    collaborator: 106,
},
{
    author_no: '7',
    author_name: 'E.L. James',
    university: 'The University of Kent',
    date_of_birth: '1984-07-27',
    h_index: 17,
    gender: 'm',
    collaborator: 107,
},
{
    author_no: '8',
    author_name: 'Edgar Allen Poe',
    university: ' University of Virginia',
    date_of_birth: '1989-04-04',
    h_index: 18,
    gender: 'm',
    collaborator: 108,
},
{
    author_no: '9',
    author_name: 'George Saunders',
    university: 'Colorado School of Mines',
    date_of_birth: '1980-06-10',
    h_index: 19,
    gender: 'm',
    collaborator: 109,
},
{
    author_no: '10',
    author_name: 'Gillian Flynn',
    university: ' Northwestern University',
    date_of_birth: '1983-04-17',
    h_index: 20,
    gender: 'm',
    collaborator: 202,
},
{
    author_no: '11',
    author_name: 'Jodi Picoult',
    university: ' Princeton University',
    date_of_birth: '1982-09-14',
    h_index: 21,
    gender: 'f',
    collaborator: 203,
},
{
    author_no: '12',
    author_name: 'Malcolm Gladwel',
    university: ' University of Toronto',
    date_of_birth: '1986-02-29',
    h_index: 22,
    gender: 'm',
    collaborator: 204,
},
{
    author_no: '13',
    author_name: 'Marissa Meye',
    university: ' Stanford University',
    date_of_birth: '1988-01-11',
    h_index: 23,
    gender: 'f',
    collaborator: 205,
},
{
    author_no: '14',
    author_name: 'Rick Yancey',
    university: 'Roosevelt University',
    date_of_birth: '1986-04-20',
    h_index: 24,
    gender: 'm',
    collaborator: 206,
},
{
    author_no: '15',
    author_name: 'Ron Chernow',
    university: 'University of Cambridge',
    date_of_birth: '1982-09-14',
    h_index: 25,
    gender: 'm',
    collaborator: 207,
},
]
module.exports = authors;